### ISSUE TITLE
Feature Request - Ad Pin form link

### ISSUE THREAD

**Issue by jm6087** [TheCre8r/WME-BackEnd-Data#11]
I would suggest that a link be added near the EP2 area to open the Misplaced Ad Pin form.  Even if not filled out, it would at least make it one less step for the editor and save them from hunting down the link.

![image](https://user-images.githubusercontent.com/24948653/52024105-2b973d80-24c5-11e9-9916-ad413203c832.png)

**Comment by subs5** [comment]
I support this request.  Other place to put it is in the BED tab similar to the link for this report an error form

**Comment by TheCre8r** [comment]
It is in beta testing, should be in production by Monday.

**Comment by jm6087** [comment]
This is working good in Beta, just need a better picture or change to "Report misplaced Ad Pin" text

**Comment by TheCre8r** [comment]
Works for "Version 2" awaiting release, then will close.

**Comment by TheCre8r** [comment]
Released in 2020.06.08.01
