### ISSUE TITLE
The Townes at Monarch not showing

### ISSUE THREAD

**Issue by subs5** [TheCre8r/WME-BackEnd-Data#13]
The ad for The Townes at Monarch did not show with the script for about 30 min.   I did a search on the screen still did not show.
  Not sure if it is supposed to be active.  This place closes at 6 pm.  I have contacted them to see if only to show during the open hours.  It appears that way in the search.

**Comment by TheCre8r** [comment]
PL for reference: https://www.waze.com/en-US/editor?env=usa&lon=-76.69317&lat=39.03075&s=608173567&zoom=5&venues=185663878.1856704319.6240755
Unable to replicate this issue. It always shows for me.
