### ISSUE TITLE
KFC/Taco Bell

### ISSUE THREAD

**Issue by jm6087** [TheCre8r/WME-BackEnd-Data#18]
I assume this is because of a google link issue in the background but.
When I click on this KFC 
https://www.waze.com/en-US/editor?env=usa&lon=-100.03088&lat=37.75409&zoom=6&venues=170393978.1703743167.3197341
![image](https://user-images.githubusercontent.com/24948653/62745610-6f897300-ba11-11e9-98f0-ba9ef8211e3d.png)

An ad pin opens for KFC at the location and an ad pin opens for Taco Bell at this location about 1/3 mile east.
https://www.waze.com/en-US/editor?env=usa&lon=-100.02686&lat=37.75370&zoom=6&venues=170393978.1703808703.1922958
![image](https://user-images.githubusercontent.com/24948653/62745632-92b42280-ba11-11e9-977e-bc8f1d91342e.png)

`{"id": "41fc659a-7934-4371-9727-4d1e74561e84","venue": {"provider_id": "1532406","provider": "WazeAds","internal_venue_id": {"t10": 170393978,"t1": 1703743167,"id": "3197341"},"categories": ["FAST_FOOD"],"name": "KFC","aliases": ["Kentucky Fried Chicken"],"location": {"x": -100.030268132,"y": 37.753836012},"services": ["PARKING_FOR_CUSTOMERS","RESTROOMS","CREDIT_CARDS","AIR_CONDITIONING","WHEELCHAIR_ACCESSIBLE","DRIVETHROUGH","TAKE_AWAY"],"house_number": "1210","street": "W Wyatt Earp Blvd","city": "Dodge City","state": "Kansas","state_full_name": "Kansas","country": "US","country_full_name": "United States","phone": "(620) 225-1241","url": "kfc.com","cityId": 8489,"street_id": 1298029,"deleted": false,"external_providers": [{"provider": "WazeAds","id": "1532406"},{"provider": "Google","id": "0x87a71b0491c772f5:0xfa42987cc2b6df9b"}],"area": 0.0,"hours": [{"from": "10:30","to": "22:00","days": [0,1,2,3,4,5,6]}],"entry_exit_points": [{"point": {"x": -100.03009378870506,"y": 37.753685443986946},"name": "","type": "ENTRY","primary": true}],"creation_date": 1459353250662,"created_by": 107668852,"last_update_date": 1565309440739,"last_update_by": [121628691],"lock_level": 2,"approved": true,"currency": "$","venue_id": "venues.170393978.1703743167.3197341","ad_keywords": ["rice bowl","fast food","restaurant","red velvet","fried chicken","popcorn chicken","take out"],"no_preview": false,"country_id": 235,"created_by_info": {"id": 0,"name": "avsus","rank": 0,"points": 0,"mood": 0,"is_staff": false,"is_registered": false,"is_ad_operator": false,"is_system_trusted": true},"last_updated_by_info": {"id": 0,"name": "jm6087","rank": 0,"points": 0,"mood": 29,"is_staff": false,"is_registered": false,"is_ad_operator": false,"is_system_trusted": true},"has_more_data": true},"price_unit": "$","info_url": "https://venues.waze.com/adview?dataprovider=venue&poi_id=170393978.1703743167.3197341&lon=-100.030268132&lat=37.753836012","info_url_append_client_data": true,"provider": "Venues","updateable": true}`

**Comment by TheCre8r** [comment]
Since Waze has changed the way they handle searching, this should be fixed.
