### ISSUE TITLE
RPP searching

### ISSUE THREAD

**Issue by jm6087** [TheCre8r/WME-BackEnd-Data#19]
Anytime I click on an RPP, I get a popup for searching.  I think I also saw parking show up in the searches, can't recall if we wanted to pull them or not.

This is in BED nightly, not sure about production or beta.

**Comment by TheCre8r** [comment]
Some parking lots do indeed have ad-pins. I need to isolate Parking Lots that are commercial and public parking lots vs lots that are for businesses.

**Comment by TheCre8r** [comment]
This should be fixed in 2020.06.08.01. Will you please confirm that you are receiving the results you intended?

**Comment by jm6087** [comment]
Looks like it is good now
Thanks
