### ISSUE TITLE
Ad Pin Layer not staying checked

### ISSUE THREAD

**Issue by jm6087** [TheCre8r/WME-BackEnd-Data#2]
If I have the ad pin layer checked, it stays checked even on reload of WME.

But, if I have the ad pin layer checked, and then deselect entire places layer.
![image](https://user-images.githubusercontent.com/24948653/50379857-8e223180-061b-11e9-9d9f-277067eb47f6.png)
And then do a hard refresh of WME, the ad pin layer is no longer selected
![image](https://user-images.githubusercontent.com/24948653/50379865-bd38a300-061b-11e9-81bc-4ff413fc44ab.png)
When I select the places layer, I have to reselect the ad pin layer.

**Comment by TheCre8r** [comment]
Issue has been confirmed to be an issue with WazeWrap. Will keep issue until it has been resolved,

**Comment by TheCre8r** [comment]
Added a temporary fix in beta, testing for release.

**Comment by jm6087** [comment]
Tested and temp fix works

**Comment by jm6087** [comment]
Ad Pins layer persists upon refresh now.
