### ISSUE TITLE
Missing Ad Pins

### ISSUE THREAD

**Issue by malevagabond81** [TheCre8r/WME-BackEnd-Data#21]
Ad pins aren't showing up on WME

**Comment by jm6087** [comment]
TheCre8r has been busy and has not had a chance to update the script.  You can use this version until he is able to update it himself.
https://github.com/TheCre8r/WME-BackEnd-Data/blob/jm6087/WME-BED.user.js

**Comment by jm6087** [comment]
This should be resolved now
