### ISSUE TITLE
Gas Prices [Italy]

### ISSUE THREAD

**Issue by giovanni-cortinovis** [TheCre8r/WME-BackEnd-Data#24]
I've added support for Italian GS Prices in this fork https://github.com/giovanni-cortinovis/WME-BackEnd-Data

**Comment by TheCre8r** [comment]
I added your code with the latest version. Will you please test the changes?

**Comment by giovanni-cortinovis** [comment]
We didin't find any issue with latest version. Thank you!

**Comment by TheCre8r** [comment]
I have since changed the way gas prices are pulled. Will you please verify it still works as intended?

**Comment by TheCre8r** [comment]
Why is Regular called Diesel and Diesel called Regular?

**Comment by jm6087** [comment]
I don't speak Italian but my research shows that
Diesel = Gasolio
Petro (regular) = Benzina
LPG = GPL
Natural Gas (gas) = Metano

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by superguru75** [comment]
These are the prices for that Gas Station displayed in the app, and all prices shown are correct. In Italy, diesel costs less than petrol. Before your last revision of the script the prices indicated with the modification by Giovanni Cortinovis were displayed correctly in the WME
![Price gas station Spinetta Marengo](https://user-images.githubusercontent.com/58091651/101267423-c663a180-3758-11eb-8e85-fe991ae411b6.jpg)

**Comment by superguru75** [comment]
[These are the prices for that Gas Station displayed in the app, and all prices shown are correct. 
In Italy, diesel costs less than petrol. Before your last revision of the script the prices indicated with the modification by Giovanni Cortinovis were displayed correctly in the WME.

![Price gas station Spinetta Marengo](https://user-images.githubusercontent.com/58091651/101267506-c021f500-3759-11eb-939f-325b624304e9.jpg)

**Comment by jm6087** [comment]
That is interesting.  The background data appears to be different
[image: image.png]
Ian will have to look into this more closely.  Are all stations showing the
same thing or is it just this one?

**Comment by superguru75** [comment]
The prices on the app, are displayed in the same order you see shown on the prices board placed near each Gas Station.
The display  order you see in the following image is a standard in all Italian Gas Stations. At the top of the list there is always the price of Diesel (Gasolio), in second position there is always the price of Benzina and in third position (if available) the price of GPL and in fourth position (if available) the price of Metano.

![price board](https://user-images.githubusercontent.com/58091651/101277104-35b9af80-37b2-11eb-99a0-4df3ea08d921.jpg)

**Comment by jm6087** [comment]
Thanks and Happy Birthday

**Comment by TheCre8r** [comment]
Thank you for the screen shot in app. The data I am pulling was coded backwards. I have made the flip that @giovanni-cortinovis had created in his fork. I have also made sure the order is sorted accordingly to what it is in app. Please confirm this is working as intended in Version 2020.12.06.01.

Thanks again for the help!

**Comment by superguru75** [comment]
Hi. 
Thanks for your update.  Now your script is working correctly.
Regards

**Comment by TheCre8r** [comment]
Thank you for the follow up.
