### ISSUE TITLE
Wrong Gas Prices updated information

### ISSUE THREAD

**Issue by Olestas** [TheCre8r/WME-BackEnd-Data#26]
Permalink: https://www.waze.com/lv/editor?env=row&lon=24.15449&lat=56.93007&s=20489175039&zoom=7&venues=15860281.158275133.115678
It says - update March31 2016 by BlackcatNr13, while actually price was updated just now.

**Comment by TheCre8r** [comment]
Can you please verify this has been resolved in the latest version?

**Comment by Olestas** [comment]
Thanks, it works now!

**Comment by jm6087** [comment]
Awesome, thanks
