### ISSUE TITLE
Incorrect update date/time/user

### ISSUE THREAD

**Issue by jm6087** [TheCre8r/WME-BackEnd-Data#27]
Permalink: https://www.waze.com/en-US/editor?env=usa&lon=-97.69734&lat=30.40793&s=18324913663&zoom=6&venues=171901232.1719012321.60749

Gas tab shows:
![image](https://user-images.githubusercontent.com/24948653/95985166-dfe80d00-0de9-11eb-8cee-45c76e5c8e99.png)

App shows:
![image](https://user-images.githubusercontent.com/24948653/95985404-2b9ab680-0dea-11eb-8430-2741b92bc220.png)

https://www.waze.com/SearchServer/mozi?lon=-97.697336&lat=30.407926&format=PROTO_JSON_FULL&venue_id=venues.171901232.1719012321.60749

**Comment by TheCre8r** [comment]
Can you please verify this has been resolved in the latest version?

**Comment by jm6087** [comment]
This appears resolved.
