### ISSUE TITLE
Gas prices on IL server

### ISSUE THREAD

**Issue by jm6087** [TheCre8r/WME-BackEnd-Data#3]
> shmupi wrote: (in forum)
>Well done !
>
>Gas prices are not getting imported on the IL server , can you please take a look ?
>Thx,
>Shmupi

**Comment by jm6087** [comment]
My reply to shmupi in the forum:

>Thanks, I will pass this on to Ian. 
>
>Can you provide a PL for a GS that does not show the prices so he can look into it?
>Are you seeing the Gas Pump tab?
>If so, can you provide a screen shot of the gas pump tab and the information you are seeing?

**Comment by TheCre8r** [comment]
On roadmap for gas station price refactoring.

**Comment by TheCre8r** [comment]
Can you please verify this has been resolved in the latest version?

**Comment by jm6087** [comment]
Verified fixed by Shmupi
https://www.waze.com/forum/viewtopic.php?f=819&t=273811&p=2106107#p2106110
