### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by andrealmeidadomingues** [TheCre8r/WME-BackEnd-Data#31]
Hello

Can you please check? 

![Captura de ecrã 2021-07-16, às 22 20 36](https://user-images.githubusercontent.com/3044459/126009660-fe1928c0-232a-4080-8e89-1e2323a9890e.png)

I can't see the add image below:
![Captura de ecrã 2021-07-16, às 22 21 12](https://user-images.githubusercontent.com/3044459/126009705-821e36b1-4ff6-4170-9fa3-a5f2d84a9451.png)

[Waze place](https://waze.com/pt-PT/editor?env=row&lat=38.69372&lon=-9.36704&zoom=6&venues=229769603.-1997074659.185605)

I have already tried to clear cache and reinstall the script. (browser: Firefox)

**Comment by TheCre8r** [comment]
Do you have an ad blocker?

**Comment by andrealmeidadomingues** [comment]
No, unless there is some new feature build in. It was working until some time ago, I didn't notice right away

**Comment by TheCre8r** [comment]
I will check it tonight and report back.

**Comment by TheCre8r** [comment]
Do you use Discord or Google Chat so we can attempt to diagnose this via chat?

**Comment by andrealmeidadomingues** [comment]
Hello,

We can chat via Google Chat if you want

**Comment by TheCre8r** [comment]
Closing this as Waze is no longer showing ads.
