### ISSUE TITLE
WME Ad Pin shows in the correct location, app displays it wrong

### ISSUE THREAD

**Issue by cgogean** [TheCre8r/WME-BackEnd-Data#34]
Since about a month ago, it looks like the ad pin BED displays is exactly on the Waze place it's tied to even though in app it shows in the wrong location. Here is one example from WME and the app.
![Screenshot_20211203-102054_Waze](https://user-images.githubusercontent.com/49620189/144627645-fdd01693-78ce-45b4-aa42-c4806e9974b5.jpg)

![WME Subway](https://user-images.githubusercontent.com/49620189/144627650-50fcd2c5-b824-458b-802d-b130754d173d.png)

**Comment by TheCre8r** [comment]
Closing this as Waze is no longer showing ads.
