### ISSUE TITLE
The ad logo is no longer displayed

### ISSUE THREAD

**Issue by TechInfoFr** [TheCre8r/WME-BackEnd-Data#37]
Hello,

For some time now, ad logos have not been displayed in WME, in France.
Good luck

**Comment by TheCre8r** [comment]
Thank you for letting me know. I am working on updating it for the new WME version. There have been some major changes in style and formatting and all need to be updated. I do not have a timeline for release, but I appreciate your patience.

**Comment by TechInfoFr** [comment]
Thanks for the quick response, and sorry for bothering. 
Thank you especially for the development 😉

**Comment by TheCre8r** [comment]
I'll close this out when I push the update.

**Comment by TheCre8r** [comment]
Or i will close this two years later, and almost a year after they stop showing ads.
