### ISSUE TITLE
New Provider Issue

### ISSUE THREAD

**Issue by tbadgley** [TheCre8r/WME-BackEnd-Data#39]
Permalink: https://www.waze.com/en-US/editor?env=usa&lon=-90.90587&lat=37.05302&s=18291874716450814&zoomLevel=18&marker=true&venues=176357747.1763511929.3530901
```json
{"provider":"Google","id":"0x87d741de46eac7b5:0x4dadf1003f34c44f","type":"PROVIDER","timestamp":1477264212374}
```

**Comment by TheCre8r** [comment]
Thank you. Looking into it now.
