### ISSUE TITLE
Click to center

### ISSUE THREAD

**Issue by RussPA-Waze** [TheCre8r/WME-BackEnd-Data#4]
To help get the GPS coords to report a bad ad pin, it would be great if you could click on an ad bubble to center it, like the crosshairs on a place work.

**Comment by jm6087** [comment]
Additional information to provide would be a PL for the Ad Pin, just in case they are several miles apart.

**Comment by TheCre8r** [comment]
I am thinking of making a modal of some sort. I am looking into a best-of-practice.

**Comment by TheCre8r** [comment]
It is in beta testing, should be in production by Monday.

**Comment by TheCre8r** [comment]
Is working in latest release.
