### ISSUE TITLE
Conflictive with "WME Place Interface Enhacements" (PIE) Script

### ISSUE THREAD

**Issue by santy2001** [TheCre8r/WME-BackEnd-Data#7]
Similar to BUG - https://github.com/TheCre8r/WME-BackEnd-Data/issues/5

This script is causing what the PIE script displays bad an icon.

BEFORE
<img width="1280" alt="captura de pantalla 2018-12-31 a la s 10 26 06 a m" src="https://user-images.githubusercontent.com/17103864/50563028-86335300-0ce7-11e9-8798-d25f518e197d.png">

AFTER
<img width="1280" alt="captura de pantalla 2018-12-31 a la s 10 27 21 a m" src="https://user-images.githubusercontent.com/17103864/50563025-83d0f900-0ce7-11e9-808e-7547bda8405b.png">

**Comment by TheCre8r** [comment]
Issue has been isolated. On the roadmap to be fixed.

**Comment by TheCre8r** [comment]
Fixed in [b0e78e4](https://github.com/TheCre8r/WME-BackEnd-Data/commit/b0e78e4640d94cd2b32ca1f106eeb5881e4542cb#diff-11889ab02876849eaf9df26ada5c7ffa)
